{% set name = "multitasking" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multitasking-{{ version }}.tar.gz
  sha256: 810640fa6670be41f4a712b287d9307a14ad849d966f06a17d2cf1593b66c3cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - multitasking
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/multitasking
  summary: Non-blocking Python methods using decorators
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kc
