{% set name = "multitasking" %}
{% set version = "0.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multitasking-{{ version }}.tar.gz
  sha256: 4d6bc3cc65f9b2dca72fb5a787850a88dae8f620c2b36ae9b55248e51bcd6026

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - multitasking
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/multitasking
  summary: Non-blocking Python methods using decorators
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kc
